### ISSUE TITLE
Error: cluster configuration already exists

### ISSUE THREAD

**Issue by itbabu** [saltstack-formulas/postgres-formula#106]
After #100 I can't run the formula on ubuntu 14.04

```salt
          ID: postgresql-cluster-prepared
    Function: cmd.run
        Name: pg_createcluster 9.5 main
      Result: False
     Comment: Command "pg_createcluster 9.5 main" run
     Started: 09:47:37.786713
    Duration: 269.437 ms
     Changes:   
              ----------
              pid:
                  11287
              retcode:
                  1
              stderr:
                  Error: cluster configuration already exists
              stdout:
```
There is no option to disable pg_createcluster on Ubuntu (?)

https://github.com/saltstack-formulas/postgres-formula/blob/e15861cb64aa9c139fa21e7b9c1e4bdc0f371680/postgres/init.sls#L28-L44
```YAML
# make sure the data directory and contents have been initialized
postgresql-cluster-prepared:
  cmd.run:
    {% if postgres.initdb %}
    - name: {{ postgres.commands.initdb }} {{ postgres.initdb_args }} -D {{ postgres.data_dir }}
    {% elif grains.os_family == 'Debian' %}
    - name: pg_createcluster {{ postgres.version }} main
    {# else: TODO #}
    {% endif %}
    - cwd: /
    - user: {{ postgres.initdb_user }}
    - unless:
      - test -f {{ postgres.data_dir }}/PG_VERSION
    - require:
      - pkg: postgresql-installed
    - env:
      LC_ALL: C.UTF-8
```
