### ISSUE TITLE
Custom tablespace state fails if run more than once

### ISSUE THREAD

**Issue by YetAnotherMinion** [saltstack-formulas/postgres-formula#145]
I can create a custom tablespace and it is created successfully. However when I rerun `state.apply` the tablespace state fails complaining that the tablespace is in the wrong place. This prevents any other changes that are applied to the database definition in the pillar from being updated because they all require the `postgres_tablespace-cutom_space`

From my pillar.sls
```yaml
    postgres:                                                                   
       ensure: present                                                           
                                                                                 
   # tablespaces to be created                                                   
   tablespaces:                                                                  
     custom_space:                                                               
       # format is /mnt/${server_identifier}/${application_owner}                
       directory: /mnt/cha-dev-play03/postgres/                                  
       owner: postgres
```
The first time I run the state.
```
----------
          ID: postgres_tablespace-custom_space
    Function: postgres_tablespace.present
        Name: custom_space
      Result: True
     Comment: The tablespace custom_space has been created
     Started: 16:14:37.791460
    Duration: 733.579 ms
     Changes:   
              ----------
              custom_space:
                  Present
```
Run the state again without changing anything
```
----------
          ID: postgres_tablespace-custom_space
    Function: postgres_tablespace.present
        Name: custom_space
      Result: False
     Comment: Tablespace custom_space is not at the right location. This is
                          unfixable without dropping and recreating the tablespace.
     Started: 16:15:28.623210
    Duration: 422.103 ms
     Changes: 
```
