### ISSUE TITLE
postgresql.dev dependency hell on RedHat

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/postgres-formula#195]
Getting `postgresql10-devel` installed on RedHat os_family is tricky due to dependencies:

- perl-Time-HiRes
- libicu-devel
- perl-IPC-Run
- perl-Test-Simple

Example errors seen
```
ID: install-postgres-dev-package
    Function: pkg.installed
        Name: postgresql10-devel
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-r01a465e6e7e44a5aa896119018df656b.scope
                    Last metadata expiration check: 0:01:19 ago on Tue Mar 20 15:46:49 2018.
                    Error: 
                     Problem 1: cannot install the best candidate for the job
                      - nothing provides perl(Time::HiRes) needed by postgresql10-devel-10.3-1PGDG.f27.x86_64
                     Problem 2: conflicting requests
                      - nothing provides perl(Time::HiRes) needed by postgresql10-devel-10.2-1PGDG.f27.x86_64
                      - nothing provides perl(Time::HiRes) needed by postgresql10-devel-10.3-1PGDG.f27.x86_64
```

**Workaround Fedora**
```
$ sudo dnf install perl-Time-HiRes libicu-devel perl-IPC-Run perl-Test-Simple -y
...
```
**Workaround Centos**
```
$ sudo yum install perl-Time-HiRes libicu-devel perl-IPC-Run perl-Test-Simple -y
...
```

Finally the state worked.
```
          ID: install-postgres-dev-package
    Function: pkg.installed
        Name: postgresql10-devel
      Result: True
     Comment: The following packages were installed/updated: postgresql10-devel
     Started: 16:18:20.696642
    Duration: 12178.273 ms
     Changes:   
              ----------
              postgresql10-devel:
                  ----------
                  new:
                      10.3-1PGDG.f27
                  old:
```
