### ISSUE TITLE
Command "service postgresql initdb" run failing on /etc/init.d/postgresql

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/postgres-formula#240]
```
----------
          ID: postgresql-cluster-prepared
    Function: cmd.run
        Name: service postgresql initdb
      Result: False
     Comment: Command "service postgresql initdb" run
     Started: 11:56:40.952677
    Duration: 87.321 ms
     Changes:   
              ----------
              pid:
                  81779
              retcode:
                  1
              stderr:
              stdout:
                  Usage: /etc/init.d/postgresql {start|stop|restart|reload|force-reload|status} [version ..]
``` 

Is there not a more modern way to iniitdb without trying /etc/init.d/postgresql ?
