### ISSUE TITLE
 Package 'libpqxx' not found

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/postgres-formula#259]
I saw this error on OpenSuSE:
```
ID: install-postgres-dev-packages
    Function: pkg.installed
      Result: False
     Comment: An error was encountered while installing package(s): Zypper command failure: Running scope as unit: run-r84d47460ebd04dcb9a196bcd8cac0bfe.scope
              Package 'libpqxx' not found.
     Started: 12:58:00.446043
    Duration: 1557.808 ms
     Changes:
```
