### ISSUE TITLE
Ubuntu installation fails due to locale setting

### ISSUE THREAD

**Issue by alexhayes** [saltstack-formulas/postgres-formula#60]
Using Vagrant to create a VirtualBox machine using a base Ubuntu 14.04 installation SLS `postgres` fails.

Without attempting to set `LC_ALL` or `LANG` the installation of the postgres package seemingly succeeds, but with a bunch of issues. For instance the `/etc/postgres` directory is not created and database initialisation fails.

There are a number of issues that appear related to this but I didn't become aware of these until I did some serious digging. See [#4543](https://github.com/saltstack/salt/issues/4543), [#19924](https://github.com/saltstack/salt/issues/19924) and [#7190](https://github.com/saltstack/salt/issues/7190).

At the very least I think the documentation should mention this, and at best include an SLS to fix the issue.

The following worked for me;

```yaml
# locale/init.sls
language-pack-en:
  pkg.installed:
    - names:
      - language-pack-en

locale-present:
  locale.present:
    - name: 'en_AU.UTF-8'

locale-system:
  locale.system:
    - name: 'en_AU.UTF-8'

configure-locale:
  cmd.run:
    - name: |
        dpkg-reconfigure locales
        update-locale LC_ALL=en_AU.UTF-8 LANG=en_AU.UTF-8
    - shell: /bin/bash
```

Note for me it wasn't enough to simply call `locale.present` and `locale.system` I had to specifically call `dpkg-reconfigure locales` and `update-locale`.
