### ISSUE TITLE
Improperly formatted top file matcher in saltenv OrderedDict([('refresh', False)]): False file

### ISSUE THREAD

**Issue by bartek** [saltstack-formulas/postgres-formula#64]
Hey all,

This is a fun one. When I would run `state.apply`, I get the following error:

```
Improperly formatted top file matcher in saltenv OrderedDict([('refresh', False)]): False file
```

I investigated heavily, and it all seem to come down to the `refresh` states being used here:

* https://github.com/saltstack-formulas/postgres-formula/blob/master/postgres/init.sls#L15
* https://github.com/saltstack-formulas/postgres-formula/blob/master/postgres/client.sls#L11

I tinkered with these to no success. Finally, I outright removed them from the state files and I was able to successfully complete my Postgres state.

For the record, here's my very slim Pillar:

```

# See example: https://github.com/saltstack-formulas/postgres-formula/blob/master/pillar.example

postgres:
  pg_hba.conf: salt://postgres/pg_hba.conf

  use_upstream_repo: False

  lookup:
    pkg: 'postgresql-9.4'
    pkg_client: 'postgresql-client-9.4'
    pg_hba: '/etc/postgresql/9.4/main/pg_hba.conf'

  # ACL management of pg_hba.conf
  # FIXME: Needs to use a specific database/Postgres users Pillar.
  acls:
    - ['local', 'db1', 'localUser']
```

Thank you for your help!

**Comment by puneetk** [comment]
@iggy tag you it

**Comment by iggy** [comment]
I don't know why that would be happening.

For clarification, you simply removed the `- refresh: {{ postgres.use_upstream_repo }}` line and it started working? If not, can you just show us exactly what you're running?

Can you share your top file?

**Comment by bartek** [comment]
@iggy 

Yup, that's the line I removed and it works now.

Which top file would help? It's basically a list of our server patterns and the wether or not to use `postgres`

**Comment by bartek** [comment]
For the record,

```
root@devsalt:~# salt --version
salt 2015.5.3 (Lithium)
```

**Comment by iggy** [comment]
Do you have more than one top file?

**Comment by bartek** [comment]
@iggy 

Yes, we have one in `pillar` and one in `salt`, the latter being for definition of states on each server.

**Comment by iggy** [comment]
Oh, yeah. More info is better. So paste whatever you can.

**Comment by bartek** [comment]
@iggy 

Sure! Here are my two top files:

**pillar/top.sls**

```

# The Pillar Top file is responsible for determining which variables
# and configuration get loaded for different environments and servers.
# No variables should be set in this file. Instead, globs should match
# the servers to load appropriate pillar files.

base:
  '*':
    - ssh
    - groups
    - users
    - openssh
    - packages/common
  'devdb*':
    - postgres/web
    - postgres/gapi
```

`postgres/web` and `postgres/gapi` are just additional specific configuration, setting `databases` and specific `users` for the `postgres` formula.

**salt/top.sls**

```
# Need to include external formulas, despite already setting them in gitfs_remotes.
include:
  - openssh
  - postgres

base:
  '*':
    - openssh
    - openssh/auth:
        - require:
            - users: common/users
    - common/packages
    - common/groups
    - common/users
  'devdb*':
    - postgres
```
