### ISSUE TITLE
First state run fails

### ISSUE THREAD

**Issue by EvaSDK** [saltstack-formulas/postgres-formula#81]
Here is the output of state.highstate:
```
----------
          ID: /etc/postgresql/9.4/main
    Function: file.directory
      Result: False
     Comment: User postgres is not available Group postgres is not available
     Started: 15:54:34.472581
    Duration: 428.798 ms
     Changes:   
----------
```

The issue is that the following block is not requiring postgres to be already installed so the file does not exist yet:
https://github.com/saltstack-formulas/postgres-formula/blob/master/postgres/init.sls#L56
