### ISSUE TITLE
postgres restarts on highstate - intended behaviour?

### ISSUE THREAD

**Issue by dahrens** [saltstack-formulas/postgres-formula#91]
we've started using the postgres formula and encountered an issue when highstating. The database server does a restart instead of a reload which leads to problems with apps using the database, which also need a restart.

I guess that the reason is inside of the [run-postgresql state](https://github.com/saltstack-formulas/postgres-formula/blob/e9e41eb12c22a3cb487a0063195444f7b84e184b/postgres/init.sls#L43).

```yaml
run-postgresql:
  service.running:
    - enable: true
    - name: {{ postgres.service }}
    - require:
      - pkg: install-postgresql
```

Are there any things done by the formula which require a restart of the service, or may this enhanced by `reload: True`?
